version: 2
jobs:
  jest:
    docker:
      - image: circleci/node:latest
      environment:
        SOURCE_BRANCH: master
        TARGET_BRANCH: gh-pages
    steps:
      # Use the NPM registry
      - run:
          name: Add NPM_TOKEN
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - checkout

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - harvestprofitapi-yarn-{{ checksum "yarn.lock" }}
            - harvestprofitapi-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: harvestprofitapi-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run jest tests
      - run:
          name: Jest Suite
          command: yarn test --ci
          environment:
            JEST_JUNIT_OUTPUT: "test_results/js-test-results.xml"

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - run:
          name: Upload Coverage
          command: ./node_modules/.bin/codecov

      # Automatically deploy docs to gh-pages
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              npm run build

              cp -a build/. out/.

              mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
              cd out

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi

workflows:
  version: 2
  jest:
    jobs:
      - jest
